curl 'https://eleapi.interno.gov.it/siel/PX/scrutiniR/DE/20251123/TE/07/RE/16' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7,fr;q=0.6' \
  -H 'cache-control: no-cache' \
  -H 'origin: https://elezioni.interno.gov.it' \
  -H 'pragma: no-cache' \
  -H 'priority: u=1, i' \
  -H 'referer: https://elezioni.interno.gov.it/' \
  -H 'sec-ch-ua: "Chromium";v="142", "Google Chrome";v="142", "Not_A Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36' -o "public/data/scrutini-puglia.json" \